name:                m03effects
version:             0.1.0.0
github:              "mikkka/m03effects"
license:             BSD3
author:              "Michael T"
maintainer:          "michael.tkachev@gmail.com"
copyright:           "2020 Michael T"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        study project 

dependencies:
- base >= 4.7 && < 5
- transformers
- mtl

library:
  source-dirs: src

executables:
  helloworld-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - m03effects
